version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod 
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    networks:
      - webnet

  celery:
    build: ./app
    command: celery --app=core worker --loglevel=info --logfile=logs/celery.log
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis
    networks:
      - webnet

  celery-beat:
    build: ./app
    command: celery --app=core beat --loglevel=info --logfile=logs/celery.log
    env_file:
      - ./.env.prod
    depends_on:
      - redis
    networks:
      - webnet
      
  redis:
    image: redis:7-alpine
    networks:
      - webnet

  dashboard:
    build: ./app
    command: celery flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis
      - celery
    networks:
      - webnet

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - webnet

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    networks:
      - webnet
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  webnet:
